### ISSUE TITLE
Factorise extractPercentID and extractStrandRandID

### ISSUE THREAD

**Issue by charles-plessy** [brennern/ScrambledTreeBuilder#2]
At the moment the two functions are doing the same thing with different variable names at the end.  Maybe you can use that core to build a more generic function that takes a column name of the `exDataFrame` object?

**Comment by brennern** [comment]
Oops @charles-plessy pressed the wrong button!

**Comment by charles-plessy** [comment]
Done by Noa in  de0516d0c69d158b88cc8b1062b3ca3bbfab0434
